### PR TITLE
BUG: Normalize loss metric names

### LINKED ISSUE #34: Dask HyperbandSearchCV and Keras Metrics crashes
Hi Adrian,
There is also a problem with the keras metrics and the HyperbandSearchCV  from dask-ml. I think this happens because there are no metrics in history on the first _warm_start_ .

<details><summary>Code:</summary>

```python
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten
from scikeras.wrappers import KerasRegressor

import numpy as np
from dask.distributed import Client, LocalCluster

import dask_ml.model_selection as dcv


def model_building_function(X, n_outputs_, hidden_layer_sizes, activation_func):
    """Dynamically build regressor."""

    model = Sequential()
    model.add(Flatten(input_shape=X.shape[1:]))
    for size in hidden_layer_sizes:
        model.add(Dense(size, activation=activation_func))
    model.add(Dense(n_outputs_))
    model.compile("adam", loss="mean_squared_error",
                  metrics=['mse', 'mae', 'logcosh']
                  )
    return model


class Est(KerasRegressor):
    def __init__(self, hidden_layer_sizes=None, activation_func=None):
        self.hidden_layer_sizes = hidden_layer_sizes
        self.activation_func = activation_func
        super().__init__()

    """
    def __call__(self, X, n_outputs_, hidden_layer_sizes, activation_func):
        model = model_building_function(
            X, n_outputs_, hidden_layer_sizes, activation_func
        )
        return model

    """
    def __call__(self, X, n_outputs_, hidden_layer_sizes, activation_func):
        print('Est args:', X, n_outputs_, hidden_layer_sizes, activation_func)

        model = model_building_function(
            X, n_outputs_, hidden_layer_sizes, activation_func
        )
        return model



if __name__ == "__main__":
    cluster = LocalCluster(processes=True, n_workers=5, threads_per_worker=1)
    # cluster = LocalCluster(processes=False, n_workers=1, threads_per_worker=1)

    dask_client = Client(cluster)
    #dask_client = Client('localhost:8786', timeout=10)



    model = KerasRegressor( build_fn=model_building_function,
                            hidden_layer_sizes=[32, 32], activation_func="relu")

    #model = Est(hidden_layer_sizes=[32, 32], activation_func="relu")
    #model = KerasRegressor(build_fn=Est(), hidden_layer_sizes=[32, 32], activation_func="relu")

    # generate data
    X = np.arange(1.0, 5001.0).reshape((100, 50)).astype(np.float32)
    y = np.arange(1.0, 101.0).reshape(100, 1).astype(np.float32)

    # specify parameters and distributions to sample from
    param_dist = {
        "hidden_layer_sizes": [[16, 16], [32, 32], [64, 64], [128, 128], [256, 256]],
        "activation_func": ["relu", "elu"],
    }

    hyperband = dcv.HyperbandSearchCV(model, param_dist, max_iter=12, aggressiveness=3,verbose=True)

    print("START HyperbandSearchCV")
    hyperband.fit(X, y)
    print("best score =", hyperband.best_score_)
    assert hasattr(hyperband, "best_score_")
```

</details>

<details><summary>Traceback</summary>
<p>

```
Traceback (most recent call last):
  File "D:\...\site-packages\distributed\utils.py", line 665, in log_errors
    yield
  File "D:\...\lib\site-packages\dask_ml\model_selection\_incremental.py", line 102, in _partial_fit
    model.partial_fit(X, y, **(fit_params or {}))
  File "D:\...\lib\site-packages\scikeras\wrappers.py", line 577, in partial_fit
    X, y, sample_weight=sample_weight, warm_start=True, **kwargs
  File "D:\...\lib\site-packages\scikeras\wrappers.py", line 548, in fit
    X, y, sample_weight=sample_weight, warm_start=warm_start, **kwargs
  File "D:\...\lib\site-packages\scikeras\wrappers.py", line 330, in _fit_keras_model
    k: self.history_[k] + hist.history[k] for k in keys
  File "D:\...\site-packages\scikeras\wrappers.py", line 330, in <dictcomp>
    k: self.history_[k] + hist.history[k] for k in keys
KeyError: 'log_cosh'
```

</p>
</details>

### PR DESCRIPTION
**Pull request by adriangb**
The name of  metrics may change when a model goes through a serialize -> deserialize round trip. It is not enough to normalize the name when the model is serialized the first time, since the `history_` attribute may be initialized with keys before the first serialization.

The solution is to have a function that normalizes metric names to the full name and use that every time `history_` is updated so that `history_` has consistent keys.

This should resolve #34.

### CODE REVIEW

**Comment by adriangb** [comment]
I'm going to leave this open for a bit before merging to see if the TF team has any input on how to "normalize" these metric names (I asked in https://github.com/tensorflow/tensorflow/pull/42097).

In the meantime, it would be great if you can test this to see if it fixes your issue @sim-san !

**Comment by sim-san** [comment]
> 
> 
> I'm going to leave this open for a bit before merging to see if the TF team has any input on how to "normalize" these metric names (I asked in [tensorflow/tensorflow#42097](https://github.com/tensorflow/tensorflow/pull/42097)).
> 
> In the meantime, it would be great if you can test this to see if it fixes your issue @sim-san !

I can confirm that your fix works. you are welcome to wait a little longer to see if the tensorflow team is still doing something

**Comment by sim-san** [comment]
But I get following error with my production:

```
Traceback (most recent call last):
  File "D:\...\lib\site-packages\distributed\utils.py", line 665, in log_errors
    yield
  File "D:\...\lib\site-packages\dask_ml\model_selection\_incremental.py", line 102, in _partial_fit
    model.partial_fit(X, y, **(fit_params or {}))
  File "D:\...\lib\site-packages\scikeras\wrappers.py", line 586, in partial_fit
    X, y, sample_weight=sample_weight, warm_start=True, **kwargs
  File "D:\...\lib\site-packages\scikeras\wrappers.py", line 557, in fit
    X, y, sample_weight=sample_weight, warm_start=warm_start, **kwargs
  File "D:\...\lib\site-packages\scikeras\wrappers.py", line 339, in _fit_keras_model
    for k in hist.history.keys()
  File "D:\...\lib\site-packages\scikeras\wrappers.py", line 339, in <dictcomp>
    for k in hist.history.keys()
  File "D:\...\lib\site-packages\scikeras\_utils.py", line 159, in get_metric_full_name
    return getattr(deserialize_metric(name), "__name__")
  File "D:\...\lib\site-packages\tensorflow\python\keras\metrics.py", line 3443, in deserialize
    printable_module_name='metric function')
  File "D:\...\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 378, in deserialize_keras_object
    'Unknown ' + printable_module_name + ': ' + object_name)
```

```
Traceback (most recent call last):
  File "D:\...\lib\site-packages\dask_ml\model_selection\_incremental.py", line 706, in fit
    return client.sync(self._fit, X, y, **fit_params)
  File "D:\...\lib\site-packages\distributed\client.py", line 780, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "D:\...\lib\site-packages\distributed\utils.py", line 348, in sync
    raise exc.with_traceback(tb)
  File "D:\...\lib\site-packages\distributed\utils.py", line 332, in f
    result[0] = yield future
  File "D:\...\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "D:\...\lib\site-packages\dask_ml\model_selection\_hyperband.py", line 402, in _fit
    *[SHAs[b]._fit(X, y, **fit_params) for b in _brackets_ids]
  File "D:\...\lib\site-packages\dask_ml\model_selection\_incremental.py", line 664, in _fit
    prefix=self.prefix,
  File "D:\...\lib\site-packages\dask_ml\model_selection\_incremental.py", line 478, in fit
    prefix=prefix,
  File "D:\...\lib\site-packages\dask_ml\model_selection\_incremental.py", line 262, in _fit
    metas = await client.gather(new_scores)
  File "D:\...\lib\site-packages\distributed\client.py", line 1752, in _gather
    raise exception.with_traceback(traceback)
  File "D:\...\lib\site-packages\dask_ml\model_selection\_incremental.py", line 102, in _partial_fit
    model.partial_fit(X, y, **(fit_params or {}))
  File "D:\...\lib\site-packages\scikeras\wrappers.py", line 586, in partial_fit
    X, y, sample_weight=sample_weight, warm_start=True, **kwargs
  File "D:\...\lib\site-packages\scikeras\wrappers.py", line 557, in fit
    X, y, sample_weight=sample_weight, warm_start=warm_start, **kwargs
  File "D:\...\lib\site-packages\scikeras\wrappers.py", line 339, in _fit_keras_model
    for k in hist.history.keys()
  File "D:\...\lib\site-packages\scikeras\wrappers.py", line 339, in <dictcomp>
    for k in hist.history.keys()
  File "D:\...\lib\site-packages\scikeras\_utils.py", line 159, in get_metric_full_name
    return getattr(deserialize_metric(name), "__name__")
  File "D:\...\lib\site-packages\tensorflow\python\keras\metrics.py", line 3443, in deserialize
    printable_module_name='metric function')
  File "D:\...\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 378, in deserialize_keras_object
    'Unknown ' + printable_module_name + ': ' + object_name)
```

**Comment by adriangb** [comment]
Can you share the actual error? And can you try without the `log_cosh`/`logcosh` metric?

**Comment by sim-san** [comment]
> Can you share the actual error? And can you try without the `log_cosh`/`logcosh` metric?

The error from https://github.com/adriangb/scikeras/pull/38#issuecomment-670405358 does not appear anymore. So everything works on my side

**Comment by adriangb** [comment]
Hmm okay interesting. I think it might have to do with the monkey patch I am doing for `log_cosh`/`logcosh` and depend on when you import things. If it works for you I guess we can merge for now but keep an eye on it.

**Comment by adriangb** [comment]
I'm going to go ahead and merge this once tests pass since it seems to solve the problem and no one has come up with a better solution (yet).

**Pull request merged**
