### PR TITLE
TST: ensure serialization doesn't affect training

### PR DESCRIPTION
**Pull request by stsievert**
**What does this PR implement?**
It implements a test to ensure model serialization doesn't affect model training.

Currently, this test fails for `optimizer="adam"` and passes for `optimizer="sgd"`. I believe this is because Adam has some internal state; it has to track the second moment estimate/etc (which is also true for RMSProp, Adagrad, Adadelta, SGD with momentum, etc). SGD without momentum doesn't have any state – the only relevant state variables are the initialization parameters.

<details>
<summary>Partial fit test</summary>

``` python
def _weights_close(model1, model2):
    w1 = [x.numpy() for x in model1.model_.weights]
    w2 = [x.numpy() for x in model2.model_.weights]
    assert len(w1) == len(w2)
    for _1, _2 in zip(w1, w2):
        assert np.allclose(_1, _2, rtol=0.01)
    return True


def _reload(model, epoch=None):
    tmp = pickle.loads(pickle.dumps(model))
    assert tmp is not model
    if epoch:
        assert tmp.current_epoch == model.current_epoch == epoch
    return tmp


@pytest.mark.parametrize("optim", ["adam", "sgd"])
def test_partial_fit_pickle(optim):
    """
    This test is implemented to make sure model pickling does not affect
    training.

    (this is essentially what Dask-ML does for search)
    """
    X, y = make_regression(n_features=8, n_samples=100)

    m1 = KerasRegressor(model=dynamic_regressor, optimizer=optim, random_state=42)
    m2 = clone(m1)

    # Make sure start from same model
    m1.partial_fit(X, y)
    m2.partial_fit(X, y)
    assert _weights_close(m1, m2)

    # Train; make sure pickling doesn't affect it
    for k in range(4):
        m1.partial_fit(X, y)
        m2 = _reload(m2, epoch=k + 1).partial_fit(X, y)

        # Make sure the same model is produced
        assert _weights_close(m1, m2)

        # Make sure predictions are the same
        assert np.allclose(m1.predict(X), m2.predict(X))

```

</details>

**Reference issues/PRs**
This test comes from the implementation in https://github.com/adriangb/scikeras/issues/70#issuecomment-723151716.

### CODE REVIEW

**Comment by adriangb** [comment]
This is awesome, thank you! I will review later tonight. The fix should be to bring in https://github.com/tensorflow/tensorflow/pull/39609 to SciKeras (at least until something like it is upstremed). I _think_ that will fix the issue. If not, we can implement custom serialization logic for optimizers.

**Comment by adriangb** [comment]
It looks like SaveModel does not save optimizer weights. Yikes. We'll have to implement custom serialization for optimizers. I wonder if this is also the case for other stateful things, like callbacks (I think some keep internal track of epochs and such).

**Comment by adriangb** [comment]
It looks like there is no easy (as in without digging deep, deep into TF) way to make this work for stateful optimizers: https://github.com/tensorflow/tensorflow/issues/44670.

**Comment by stsievert** [comment]
> We'll have to implement custom serialization for optimizers.

Can you expand on https://github.com/tensorflow/tensorflow/pull/42749#issuecomment-723414141? I'm confused on the difference between "slots" and "weights".

It looks like `Optimizer._create_all_weights` ([source][2]) is used during initialization ([source][4]). Would that be useful?

[3]:https://github.com/tensorflow/tensorflow/blob/15ffb9d4fb9a440a5b355e3064f8737a435f872c/tensorflow/python/keras/optimizer_v2/adadelta.py#L96
[1]:https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Optimizer
[2]:https://github.com/tensorflow/tensorflow/blob/15ffb9d4fb9a440a5b355e3064f8737a435f872c/tensorflow/python/keras/optimizer_v2/optimizer_v2.py#L761-L772
[4]:https://github.com/tensorflow/tensorflow/blob/15ffb9d4fb9a440a5b355e3064f8737a435f872c/tensorflow/python/keras/optimizer_v2/optimizer_v2.py#L596-L597

**Comment by adriangb** [comment]
> Can you expand on [tensorflow/tensorflow#42749 (comment)](https://github.com/tensorflow/tensorflow/pull/42749#issuecomment-723414141)? I'm confused on the difference between "slots" and "weights".

It seems that the issue is related to optimizers that have "slots" (based on https://github.com/tensorflow/tensorflow/pull/42749#issuecomment-683964931). I think that "slots" are an implementation detail in TF; [this](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Optimizer#slots_2) is the only information I could find in the docs. TL;DR I'm just as confused as you about this slots thing.

> It looks like `Optimizer._create_all_weights` ([source](https://github.com/tensorflow/tensorflow/blob/15ffb9d4fb9a440a5b355e3064f8737a435f872c/tensorflow/python/keras/optimizer_v2/optimizer_v2.py#L761-L772)) is used during initialization ([source](https://github.com/tensorflow/tensorflow/blob/15ffb9d4fb9a440a5b355e3064f8737a435f872c/tensorflow/python/keras/optimizer_v2/optimizer_v2.py#L596-L597)). Would that be useful?

Maybe. I'd have to spend some time with it, I'm pretty unfamiliar with the inner workings of this part of TF. I also am not sure that we should be depending on implementations of private functions within TF, even if we are able to figure out how it all works.

Let's at least wait until next week to see if there are any updates to https://github.com/tensorflow/tensorflow/issues/44670 or https://github.com/tensorflow/tensorflow/pull/42749. I also saw https://github.com/tensorflow/community/pull/281 where there is a question about this specific issue (https://github.com/tensorflow/community/pull/281#issuecomment-715596624).

**Comment by adriangb** [comment]
A useful representation of the actual "state" that these optimizers have: https://github.com/geohot/tinygrad/blob/35a5c82a2aba057f89725a485aed994aba50eebe/tinygrad/optim.py

**Comment by adriangb** [comment]
@stsievert should we close this since these tests were incorporated in #128 ?

**Comment by stsievert** [comment]
I've added a note in the test to refer back to this PR for more detail (to provide more context). Merge this PR instead?

**Comment by adriangb** [comment]
> I've added a note in the test to refer back to this PR for more detail (to provide more context). Merge this PR instead?

Awesome, thank you for adding the notes, they look great. I'll merge this as you suggest.

**Pull request merged**
